### ISSUE TITLE
Construcción de la ventana1 primera parte

### ISSUE THREAD

**Issue by Gaby0320** [Gaby0320/Clase9#1]
Construir la ventana ventana1() y hacer el formulario para ingresar la información del cliente

**Comment by michibonnet2** [comment]
Voy a encargarme de esta funcionalidad

**Comment by 97lys** [comment]
yo me encargo de este

**Comment by 97lys** [comment]
trabajo cumplido por favor revisar el nuevo issue para hacer en ventana1.py el formulario de registro del usuario
